### ISSUE TITLE
Megalodon Merge Todo List

### ISSUE THREAD

**Issue by kablouser** [kablouser/PlatinumEngine#60]
DON'T CLICK "Convert to issue"

- [x] Audio loader needs to added back. Copy the code from before the merge because it's been deleted. (assigned to Jason)

Serialization. These classes need a CreateTypeInfo function:
- [x] AnimationComponent, tidy up data so serialization is easier (assigned to Shihua)
- [x] RigidBody, BoxCollider, SphereCollider, CapsuleCollider, PhysicsMaterial (assigned to Jason)
- [x] Maths::Vec4 (assigned to Jason)
- [x] ParticleEffect (assigned to Matt (probably))
- [x] AudioComponent (assigned to Jason)
